/*
 *   This file will be regenerated by `mulle-project-versioncheck`.
 *   Any edits will be lost.
 */
#ifndef mulle_slug_versioncheck_h__
#define mulle_slug_versioncheck_h__

#if defined( MULLE__BUFFER_VERSION)
# ifndef MULLE__BUFFER_VERSION_MIN
#  define MULLE__BUFFER_VERSION_MIN  ((3UL << 20) | (5 << 8) | 0)
# endif
# ifndef MULLE__BUFFER_VERSION_MAX
#  define MULLE__BUFFER_VERSION_MAX  ((4UL << 20) | (0 << 8) | 0)
# endif
# if MULLE__BUFFER_VERSION < MULLE__BUFFER_VERSION_MIN
#  error "mulle-buffer is too old"
# endif
# if MULLE__BUFFER_VERSION >= MULLE__BUFFER_VERSION_MAX
#  error "mulle-buffer is too new"
# endif
#endif

#if defined( MULLE__UTF_VERSION)
# ifndef MULLE__UTF_VERSION_MIN
#  define MULLE__UTF_VERSION_MIN  ((4UL << 20) | (0 << 8) | 0)
# endif
# ifndef MULLE__UTF_VERSION_MAX
#  define MULLE__UTF_VERSION_MAX  ((5UL << 20) | (0 << 8) | 0)
# endif
# if MULLE__UTF_VERSION < MULLE__UTF_VERSION_MIN
#  error "mulle-utf is too old"
# endif
# if MULLE__UTF_VERSION >= MULLE__UTF_VERSION_MAX
#  error "mulle-utf is too new"
# endif
#endif

#endif
