/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_container_debug_include_h__
#define _mulle_container_debug_include_h__

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove mulle-c11`
// (Use 219C3290-98C4-46E8-91FE-8F9E62B98360 instead of mulle-c11, if there are duplicate entries)
//
// You can tweak the following #include with these commands:
//    remove #include: `mulle-sde dependency mark mulle-c11 no-header`
//    rename              : `mulle-sde dependency|library set mulle-c11 include whatever.h`
//    reorder             : `mulle-sde dependency move mulle-c11 <up|down>`
//    toggle #include: `mulle-sde dependency mark mulle-c11 [no-]import`
//    toggle public       : `mulle-sde dependency mark mulle-c11 [no-]public`
//    toggle optional     : `mulle-sde dependency mark mulle-c11 [no-]require`
//    remove for platform : `mulle-sde dependency mark mulle-c11 no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-c11/mulle-c11.h>   // mulle-c11

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove mulle-buffer`
// (Use 95C23FBC-93AE-4877-A6F3-AC64A607CB73 instead of mulle-buffer, if there are duplicate entries)
//
// You can tweak the following #include with these commands:
//    remove #include: `mulle-sde dependency mark mulle-buffer no-header`
//    rename              : `mulle-sde dependency|library set mulle-buffer include whatever.h`
//    reorder             : `mulle-sde dependency move mulle-buffer <up|down>`
//    toggle #include: `mulle-sde dependency mark mulle-buffer [no-]import`
//    toggle public       : `mulle-sde dependency mark mulle-buffer [no-]public`
//    toggle optional     : `mulle-sde dependency mark mulle-buffer [no-]require`
//    remove for platform : `mulle-sde dependency mark mulle-buffer no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-buffer/mulle-buffer.h>   // mulle-buffer

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove mulle-container`
// (Use 94398F0C-B5ED-4EB9-9A69-9C42E3B50A3B instead of mulle-container, if there are duplicate entries)
//
// You can tweak the following #include with these commands:
//    remove #include: `mulle-sde dependency mark mulle-container no-header`
//    rename              : `mulle-sde dependency|library set mulle-container include whatever.h`
//    reorder             : `mulle-sde dependency move mulle-container <up|down>`
//    toggle #include: `mulle-sde dependency mark mulle-container [no-]import`
//    toggle public       : `mulle-sde dependency mark mulle-container [no-]public`
//    toggle optional     : `mulle-sde dependency mark mulle-container [no-]require`
//    remove for platform : `mulle-sde dependency mark mulle-container no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-container/mulle-container.h>   // mulle-container

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove mulle-sprintf`
// (Use 8C3EA5B6-60B0-48C7-B94B-2D6CB3CD8D70 instead of mulle-sprintf, if there are duplicate entries)
//
// You can tweak the following #include with these commands:
//    remove #include: `mulle-sde dependency mark mulle-sprintf no-header`
//    rename              : `mulle-sde dependency|library set mulle-sprintf include whatever.h`
//    reorder             : `mulle-sde dependency move mulle-sprintf <up|down>`
//    toggle #include: `mulle-sde dependency mark mulle-sprintf [no-]import`
//    toggle public       : `mulle-sde dependency mark mulle-sprintf [no-]public`
//    toggle optional     : `mulle-sde dependency mark mulle-sprintf [no-]require`
//    remove for platform : `mulle-sde dependency mark mulle-sprintf no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-sprintf/mulle-sprintf.h>   // mulle-sprintf

#endif
