/*
 *   This file will be regenerated by `mulle-match-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_MATCH_TO_C_C_HEADERS_FILE DISABLE
 *
 *   To not let mulle-match-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_MATCH_TO_C_RUN DISABLE
 */
#ifndef _mulle__container__debug__provide_h__
#define _mulle__container__debug__provide_h__


#include "mulle--array-debug.h"
#include "mulle-array-debug.h"
#include "mulle-flexarray-debug.h"
#include "mulle--pointerarray-debug.h"
#include "mulle-pointerarray-debug.h"
#include "mulle--structarray-debug.h"
#include "mulle-structarray-debug.h"
#include "mulle--assoc-debug.h"
#include "mulle-assoc-debug.h"
#include "mulle--pointerpairarray-debug.h"
#include "mulle-pointerpairarray-debug.h"
#include "mulle-pointerpair-debug.h"
#include "mulle--map-debug.h"
#include "mulle-map-debug.h"
#include "mulle--pointermap-debug.h"
#include "mulle--pointermap-generic-debug.h"
#include "mulle--pointermap-struct-debug.h"
#include "mulle--pointerqueue-debug.h"
#include "mulle-pointerqueue-debug.h"
#include "mulle--structqueue-debug.h"
#include "mulle-structqueue-debug.h"
#include "mulle--rangeset-debug.h"
#include "mulle--set-debug.h"
#include "mulle-set-debug.h"
#include "mulle--pointerset-debug.h"
#include "mulle-pointerset-debug.h"
#include "mulle--pointerset-generic-debug.h"
#include "mulle--pointerset-struct-debug.h"


#endif
