#ifndef mulle__container__debug_h__
#define mulle__container__debug_h__

#include "include.h"

#include <stdint.h>

/*
 *  (c) 2023 mulle-kybernetik-tv <|ORGANIZATION|>
 *
 *  version:  major, minor, patch
 */
#define MULLE__CONTAINER__DEBUG_VERSION  ((0UL << 20) | (1 << 8) | 0)


static inline unsigned int   mulle_container_debug_get_version_major( void)
{
   return( MULLE__CONTAINER__DEBUG_VERSION >> 20);
}


static inline unsigned int   mulle_container_debug_get_version_minor( void)
{
   return( (MULLE__CONTAINER__DEBUG_VERSION >> 8) & 0xFFF);
}


static inline unsigned int   mulle_container_debug_get_version_patch( void)
{
   return( MULLE__CONTAINER__DEBUG_VERSION & 0xFF);
}


MULLE__CONTAINER__DEBUG_GLOBAL
uint32_t   mulle_container_debug_get_version( void);


/*
 * The following files are auto-generated.
 * The _mulle-container-debug-provide header is generated by
 * mulle-match-to-c during a reflect.
 */
#include "_mulle-container-debug-provide.h"

/*
 * The versioncheck header can be generated with
 * mulle-project-dependency-versions, but it is optional.
 */
#ifdef __has_include
# if __has_include( "_mulle-container-debug-versioncheck-debug.h")
#  include "_mulle-container-debug-versioncheck.h"
# endif
#endif

#endif
