//
//  mulle-container-debug.h
//  mulle-container-debug
//
//  Copyright (c) 2024 Nat! - Mulle kybernetiK.
//  All rights reserved.
//
//
//  Redistribution and use in source and binary forms, with or without
//  modification, are permitted provided that the following conditions are met:
//
//  Redistributions of source code must retain the above copyright notice, this
//  list of conditions and the following disclaimer.
//
//  Redistributions in binary form must reproduce the above copyright notice,
//  this list of conditions and the following disclaimer in the documentation
//  and/or other materials provided with the distribution.
//
//  Neither the name of Mulle kybernetiK nor the names of its contributors
//  may be used to endorse or promote products derived from this software
//  without specific prior written permission.
//
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
//  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
//  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
//  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
//  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
//  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
//  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
//  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
//  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
//  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
//  POSSIBILITY OF SUCH DAMAGE.
//
#ifndef mulle__container__debug_h__
#define mulle__container__debug_h__

#include "include.h"

#include <stdint.h>

/*
 *  (c) 2023 mulle-kybernetik-tv <|ORGANIZATION|>
 *
 *  version:  major, minor, patch
 */
#define MULLE__CONTAINER__DEBUG_VERSION  ((0UL << 20) | (1 << 8) | 3)


static inline unsigned int   mulle_container_debug_get_version_major( void)
{
   return( MULLE__CONTAINER__DEBUG_VERSION >> 20);
}


static inline unsigned int   mulle_container_debug_get_version_minor( void)
{
   return( (MULLE__CONTAINER__DEBUG_VERSION >> 8) & 0xFFF);
}


static inline unsigned int   mulle_container_debug_get_version_patch( void)
{
   return( MULLE__CONTAINER__DEBUG_VERSION & 0xFF);
}


MULLE__CONTAINER__DEBUG_GLOBAL
uint32_t   mulle_container_debug_get_version( void);


/*
 * The following files are auto-generated.
 * The _mulle-container-debug-provide header is generated by
 * mulle-match-to-c during a reflect.
 */
#include "_mulle-container-debug-provide.h"

/*
 * The versioncheck header can be generated with
 * mulle-project-dependency-versions, but it is optional.
 */
#ifdef __has_include
# if __has_include( "_mulle-container-debug-versioncheck-debug.h")
#  include "_mulle-container-debug-versioncheck.h"
# endif
#endif

#endif
