#ifndef mulle__time_include_h__
#define mulle__time_include_h__

// this is a global symbol that is exposed, which can be used to detect
// if this library is available

#define HAVE_INCLUDE_MULLE__TIME

/* DO:    #include this files in public headers.

   DONT:  #include this files in private headers.
          #include this file directly in sources.
          #import this file anywhere (except in import.h)
 */


/* This is a central include file to keep dependencies out of the library
   C files. It is usually included by .h files only.

   As the name "include.h" is standardized across mulle-sde projects,
   .c and .h files are now  motile. They can be moved to other projects and
   don't need to be edited.

   If you delete it, it will not be regenerated.
*/

/*
 * Include the header file generated by mulle-sde reflect.
 */

#include "_mulle-time-include.h"


// this is for WIN32: specify global non-inlined functions and variables
// like this (can not be declared inside functions!)
//
// .h:
// #include "include.h"
// MULLE__TIME_GLOBAL char *   aGlobalString;
// MULLE__TIME_GLOBAL void     aGlobalFunction( void);
//
// .c:
// #include "include-private.h"
// MULLE__TIME_GLOBAL_VAR
// char *  aGlobalString = "VfL Bochum 1848";
// MULLE__TIME_GLOBAL
// void   aGlobalFunction( void) {}
//
#ifndef MULLE__TIME_GLOBAL
# ifdef MULLE__TIME_BUILD
#  define MULLE__TIME_GLOBAL       MULLE_C_GLOBAL
#  define MULLE__TIME_GLOBAL_VAR   MULLE_C_GLOBAL
# else
#  if defined( MULLE__TIME_INCLUDE_DYNAMIC) || (defined( MULLE_INCLUDE_DYNAMIC) && ! defined( MULLE__TIME_INCLUDE_STATIC))
#   define MULLE__TIME_GLOBAL      MULLE_C_GLOBAL
#  else
#   define MULLE__TIME_GLOBAL      extern
#  endif
# endif
# define MULLE__TIME_GLOBAL_VAR    MULLE_C_GLOBAL
#endif

/* You can add some more include statements here */

#endif
