/*
 *   This file will be regenerated by `mulle-project-versioncheck`.
 *   Any edits will be lost.
 */
#ifndef mulle_rbtree_versioncheck_h__
#define mulle_rbtree_versioncheck_h__

#if defined( MULLE__STORAGE_VERSION)
# ifndef MULLE__STORAGE_VERSION_MIN
#  define MULLE__STORAGE_VERSION_MIN  ((0UL << 20) | (0 << 8) | 4)
# endif
# ifndef MULLE__STORAGE_VERSION_MAX
#  define MULLE__STORAGE_VERSION_MAX  ((0UL << 20) | (1 << 8) | 0)
# endif
# if MULLE__STORAGE_VERSION < MULLE__STORAGE_VERSION_MIN || MULLE__STORAGE_VERSION >= MULLE__STORAGE_VERSION_MAX
#  pragma message("MULLE__STORAGE_VERSION     is " MULLE_C_STRINGIFY_MACRO( MULLE__STORAGE_VERSION))
#  pragma message("MULLE__STORAGE_VERSION_MIN is " MULLE_C_STRINGIFY_MACRO( MULLE__STORAGE_VERSION_MIN))
#  pragma message("MULLE__STORAGE_VERSION_MAX is " MULLE_C_STRINGIFY_MACRO( MULLE__STORAGE_VERSION_MAX))
#  if MULLE__STORAGE_VERSION < MULLE__STORAGE_VERSION_MIN
#   error "mulle-storage is too old"
#  else
#   error "mulle-storage is too new"
#  endif
# endif
#endif

#endif
