/*
 *   This file will be regenerated by `mulle-project-versioncheck`.
 *   Any edits will be lost.
 */
#ifndef mulle_rbtree_versioncheck_h__
#define mulle_rbtree_versioncheck_h__

#if defined( MULLE__STORAGE_VERSION)
# ifndef MULLE__STORAGE_VERSION_MIN
#  define MULLE__STORAGE_VERSION_MIN  ((0UL << 20) | (0 << 8) | 2)
# endif
# ifndef MULLE__STORAGE_VERSION_MAX
#  define MULLE__STORAGE_VERSION_MAX  ((0UL << 20) | (1 << 8) | 0)
# endif
# if MULLE__STORAGE_VERSION < MULLE__STORAGE_VERSION_MIN
#  error "mulle-storage is too old"
# endif
# if MULLE__STORAGE_VERSION >= MULLE__STORAGE_VERSION_MAX
#  error "mulle-storage is too new"
# endif
#endif

#endif
