/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_regex_include_h__
#define _mulle_regex_include_h__

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove mulle-utf`
// (Use DA632302-CC77-41E3-A7C2-16F226549339 instead of mulle-utf, if there are duplicate entries)
//
// You can tweak the following #include with these commands:
//    remove #include: `mulle-sde dependency mark mulle-utf no-header`
//    rename              : `mulle-sde dependency|library set mulle-utf include whatever.h`
//    reorder             : `mulle-sde dependency move mulle-utf <up|down>`
//    toggle #include: `mulle-sde dependency mark mulle-utf [no-]import`
//    toggle public       : `mulle-sde dependency mark mulle-utf [no-]public`
//    toggle optional     : `mulle-sde dependency mark mulle-utf [no-]require`
//    remove for platform : `mulle-sde dependency mark mulle-utf no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-utf/mulle-utf.h>   // mulle-utf

#endif
