/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_dlfcn_include_h__
#define _mulle_dlfcn_include_h__

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove mulle-c11`
// (Use A3ED849C-ECFE-4FB8-8E50-D5245D67E30B instead of mulle-c11, if there are duplicate entries)
//
// You can tweak the following #include with these commands:
//    remove #include: `mulle-sde dependency mark mulle-c11 no-header`
//    rename              : `mulle-sde dependency|library set mulle-c11 include whatever.h`
//    reorder             : `mulle-sde dependency move mulle-c11 <up|down>`
//    toggle #include: `mulle-sde dependency mark mulle-c11 [no-]import`
//    toggle public       : `mulle-sde dependency mark mulle-c11 [no-]public`
//    toggle optional     : `mulle-sde dependency mark mulle-c11 [no-]require`
//    remove for platform : `mulle-sde dependency mark mulle-c11 no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-c11/mulle-c11.h>   // mulle-c11

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove dlfcn-win32`
// (Use 8D2BE61C-D741-4FCC-8A99-5EB39BBE7A3E instead of dlfcn-win32, if there are duplicate entries)
//
// You can tweak the following #include with these commands:
//    remove #include: `mulle-sde dependency mark dlfcn-win32 no-header`
//    rename              : `mulle-sde dependency|library set dlfcn-win32 include whatever.h`
//    reorder             : `mulle-sde dependency move dlfcn-win32 <up|down>`
//    toggle #include: `mulle-sde dependency mark dlfcn-win32 [no-]import`
//    toggle public       : `mulle-sde dependency mark dlfcn-win32 [no-]public`
//    toggle optional     : `mulle-sde dependency mark dlfcn-win32 [no-]require`
//    remove for platform : `mulle-sde dependency mark dlfcn-win32 no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
# if defined( _WIN32) || defined( _WIN32)
# include <dlfcn.h>   // dlfcn-win32
#endif

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove dl`
// (Use 3035297A-114F-447F-AA5A-EDF4E3B174B6 instead of dl, if there are duplicate entries)
//
// You can tweak the following #include with these commands:
//    remove #include: `mulle-sde dependency mark dl no-header`
//    rename              : `mulle-sde dependency|library set dl include whatever.h`
//    reorder             : `mulle-sde dependency move dl <up|down>`
//    toggle #include: `mulle-sde dependency mark dl [no-]import`
//    toggle public       : `mulle-sde dependency mark dl [no-]public`
//    toggle optional     : `mulle-sde dependency mark dl [no-]require`
//    remove for platform : `mulle-sde dependency mark dl no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
# if ! defined( _WIN32) && ! defined( _WIN32)
# ifdef __has_include
#  if __has_include(<dlfcn.h>)
#    include <dlfcn.h>   // dl
#   define HAVE_LIB_DL
#  endif
# endif
#endif

#endif
