/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_linkedlist_include_h__
#define _mulle_linkedlist_include_h__

// You can tweak the following #include with these commands.
// (Use 565E6B7F-36C7-45DE-BE97-8B2EA49467F0 instead of mulle-c11 if there are duplicate entries)
//    remove #include:: `mulle-sde dependency mark mulle-c11 no-header`
//    rename:              `mulle-sde dependency|library set mulle-c11 include whatever.h`
//    reorder:             `mulle-sde dependency move mulle-c11 <up|down>`
//    toggle #include:    `mulle-sde dependency mark mulle-c11 [no-]import`
//    toggle public:       `mulle-sde dependency mark mulle-c11 [no-]public`
//    toggle optional:     `mulle-sde dependency mark mulle-c11 [no-]require`
//    remove for platform: `mulle-sde dependency mark mulle-c11 no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-c11/mulle-c11.h>   // mulle-c11

// You can tweak the following #include with these commands.
// (Use 74A4D13C-700D-40AD-9C03-836D573181B5 instead of mulle-allocator if there are duplicate entries)
//    remove #include:: `mulle-sde dependency mark mulle-allocator no-header`
//    rename:              `mulle-sde dependency|library set mulle-allocator include whatever.h`
//    reorder:             `mulle-sde dependency move mulle-allocator <up|down>`
//    toggle #include:    `mulle-sde dependency mark mulle-allocator [no-]import`
//    toggle public:       `mulle-sde dependency mark mulle-allocator [no-]public`
//    toggle optional:     `mulle-sde dependency mark mulle-allocator [no-]require`
//    remove for platform: `mulle-sde dependency mark mulle-allocator no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-allocator/mulle-allocator.h>   // mulle-allocator

// You can tweak the following #include with these commands.
// (Use 72DD46E1-BD79-4C47-BBE3-A8448989BABC instead of mulle-thread if there are duplicate entries)
//    remove #include:: `mulle-sde dependency mark mulle-thread no-header`
//    rename:              `mulle-sde dependency|library set mulle-thread include whatever.h`
//    reorder:             `mulle-sde dependency move mulle-thread <up|down>`
//    toggle #include:    `mulle-sde dependency mark mulle-thread [no-]import`
//    toggle public:       `mulle-sde dependency mark mulle-thread [no-]public`
//    toggle optional:     `mulle-sde dependency mark mulle-thread [no-]require`
//    remove for platform: `mulle-sde dependency mark mulle-thread no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-thread/mulle-thread.h>   // mulle-thread

#endif
