/*
 *   This file will be regenerated by `mulle-project-versioncheck`.
 *   Any edits will be lost.
 */
#if defined( MULLE_DLFCN_VERSION)
# if MULLE_DLFCN_VERSION < ((0 << 20) | (0 << 8) | 11)
#  error "mulle-dlfcn is too old"
# endif
# if MULLE_DLFCN_VERSION >= ((0 << 20) | (1 << 8) | 0)
#  error "mulle-dlfcn is too new"
# endif
#endif
