/*
 *   This file will be regenerated by `mulle-match-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_MATCH_TO_C_C_HEADERS_FILE DISABLE
 *
 *   To not let mulle-match-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_MATCH_TO_C_RUN DISABLE
 */
#include "mulle-unicode-is-nonpercentescape.h"
#include "mulle-unicode-is-validurlfragment.h"
#include "mulle-unicode-is-validurlhost.h"
#include "mulle-unicode-is-validurlpassword.h"
#include "mulle-unicode-is-validurlpath.h"
#include "mulle-unicode-is-validurlquery.h"
#include "mulle-unicode-is-validurlscheme.h"
#include "mulle-unicode-is-validurluser.h"
