/*
 *   This file will be regenerated by `mulle-project-versioncheck`.
 *   Any edits will be lost.
 */
#ifndef mulle_fprintf_versioncheck_h__
#define mulle_fprintf_versioncheck_h__

#if defined( MULLE__SPRINTF_VERSION)
# ifndef MULLE__SPRINTF_VERSION_MIN
#  define MULLE__SPRINTF_VERSION_MIN  ((3UL << 20) | (3 << 8) | 0)
# endif
# ifndef MULLE__SPRINTF_VERSION_MAX
#  define MULLE__SPRINTF_VERSION_MAX  ((4UL << 20) | (0 << 8) | 0)
# endif
# if MULLE__SPRINTF_VERSION < MULLE__SPRINTF_VERSION_MIN || MULLE__SPRINTF_VERSION >= MULLE__SPRINTF_VERSION_MAX
#  pragma message("MULLE__SPRINTF_VERSION     is " MULLE_C_STRINGIFY_MACRO( MULLE__SPRINTF_VERSION))
#  pragma message("MULLE__SPRINTF_VERSION_MIN is " MULLE_C_STRINGIFY_MACRO( MULLE__SPRINTF_VERSION_MIN))
#  pragma message("MULLE__SPRINTF_VERSION_MAX is " MULLE_C_STRINGIFY_MACRO( MULLE__SPRINTF_VERSION_MAX))
#  if MULLE__SPRINTF_VERSION < MULLE__SPRINTF_VERSION_MIN
#   error "mulle-sprintf is too old"
#  else
#   error "mulle-sprintf is too new"
#  endif
# endif
#endif

#endif
