/*
 *   This file will be regenerated by `mulle-project-versioncheck`.
 *   Any edits will be lost.
 */
#if defined( MULLE_SPRINTF_VERSION)
# if MULLE_SPRINTF_VERSION < ((3 << 20) | (0 << 8) | 0)
#  error "mulle-sprintf is too old"
# endif
# if MULLE_SPRINTF_VERSION >= ((4 << 20) | (0 << 8) | 0)
#  error "mulle-sprintf is too new"
# endif
#endif
