/*
 *   This file will be regenerated by `mulle-match-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_MATCH_TO_C_C_HEADERS_FILE DISABLE
 *
 *   To not let mulle-match-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_MATCH_TO_C_RUN DISABLE
 */
#ifndef mulle_fifo_provide_h__
#define mulle_fifo_provide_h__


#include "mulle--pointerfifo1024.h"
#include "mulle--pointerfifo128.h"
#include "mulle--pointerfifo16.h"
#include "mulle--pointerfifo2048.h"
#include "mulle--pointerfifo256.h"
#include "mulle--pointerfifo32.h"
#include "mulle--pointerfifo4096.h"
#include "mulle--pointerfifo4.h"
#include "mulle--pointerfifo512.h"
#include "mulle--pointerfifo64.h"
#include "mulle--pointerfifo8192.h"
#include "mulle--pointerfifo8.h"
#include "mulle-pointerfifo.h"


#endif
