/*
 *   This file will be regenerated by `mulle-match-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_MATCH_TO_C_C_HEADERS_FILE DISABLE
 *
 *   To not let mulle-match-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_MATCH_TO_C_RUN DISABLE
 */
#ifndef _mulle__utf__provide_h__
#define _mulle__utf__provide_h__


#include "mulle-ascii.h"
#include "mulle-char5.h"
#include "mulle-char7.h"
#include "mulle-utf16.h"
#include "mulle-utf16-string.h"
#include "mulle-utf32.h"
#include "mulle-utf32-string.h"
#include "mulle-utf8.h"
#include "mulle-utf8-string.h"
#include "mulle-utf-convenience.h"
#include "mulle-utf-noncharacter.h"
#include "mulle-utf-privatecharacter.h"
#include "mulle-utf-rover.h"
#include "mulle-utf-scan.h"
#include "mulle-utf-type.h"


#endif
