/*
 *   This file will be regenerated by `mulle-project-versioncheck`.
 *   Any edits will be lost.
 */
#ifndef mulle_rbtree_debug_versioncheck_h__
#define mulle_rbtree_debug_versioncheck_h__

#if defined( MULLE__FPRINTF_VERSION)
# ifndef MULLE__FPRINTF_VERSION_MIN
#  define MULLE__FPRINTF_VERSION_MIN  ((0UL << 20) | (3 << 8) | 2)
# endif
# ifndef MULLE__FPRINTF_VERSION_MAX
#  define MULLE__FPRINTF_VERSION_MAX  ((0UL << 20) | (4 << 8) | 0)
# endif
# if MULLE__FPRINTF_VERSION < MULLE__FPRINTF_VERSION_MIN || MULLE__FPRINTF_VERSION >= MULLE__FPRINTF_VERSION_MAX
#  pragma message("MULLE__FPRINTF_VERSION     is " MULLE_C_STRINGIFY_MACRO( MULLE__FPRINTF_VERSION))
#  pragma message("MULLE__FPRINTF_VERSION_MIN is " MULLE_C_STRINGIFY_MACRO( MULLE__FPRINTF_VERSION_MIN))
#  pragma message("MULLE__FPRINTF_VERSION_MAX is " MULLE_C_STRINGIFY_MACRO( MULLE__FPRINTF_VERSION_MAX))
#  if MULLE__FPRINTF_VERSION < MULLE__FPRINTF_VERSION_MIN
#   error "mulle-fprintf is too old"
#  else
#   error "mulle-fprintf is too new"
#  endif
# endif
#endif
#if defined( MULLE__RBTREE_VERSION)
# ifndef MULLE__RBTREE_VERSION_MIN
#  define MULLE__RBTREE_VERSION_MIN  ((0UL << 20) | (1 << 8) | 0)
# endif
# ifndef MULLE__RBTREE_VERSION_MAX
#  define MULLE__RBTREE_VERSION_MAX  ((0UL << 20) | (2 << 8) | 0)
# endif
# if MULLE__RBTREE_VERSION < MULLE__RBTREE_VERSION_MIN || MULLE__RBTREE_VERSION >= MULLE__RBTREE_VERSION_MAX
#  pragma message("MULLE__RBTREE_VERSION     is " MULLE_C_STRINGIFY_MACRO( MULLE__RBTREE_VERSION))
#  pragma message("MULLE__RBTREE_VERSION_MIN is " MULLE_C_STRINGIFY_MACRO( MULLE__RBTREE_VERSION_MIN))
#  pragma message("MULLE__RBTREE_VERSION_MAX is " MULLE_C_STRINGIFY_MACRO( MULLE__RBTREE_VERSION_MAX))
#  if MULLE__RBTREE_VERSION < MULLE__RBTREE_VERSION_MIN
#   error "mulle-rbtree is too old"
#  else
#   error "mulle-rbtree is too new"
#  endif
# endif
#endif

#endif
