/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_rbtree_debug_include_h__
#define _mulle_rbtree_debug_include_h__

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove mulle-rbtree`
// (Use 8DB1697D-A19C-40A1-A1A8-8DE1A4444CC2 instead of mulle-rbtree, if there are duplicate entries)
//
// You can tweak the following #include with these commands:
//    remove #include: `mulle-sde dependency mark mulle-rbtree no-header`
//    rename              : `mulle-sde dependency|library set mulle-rbtree include whatever.h`
//    reorder             : `mulle-sde dependency move mulle-rbtree <up|down>`
//    toggle #include: `mulle-sde dependency mark mulle-rbtree [no-]import`
//    toggle public       : `mulle-sde dependency mark mulle-rbtree [no-]public`
//    toggle optional     : `mulle-sde dependency mark mulle-rbtree [no-]require`
//    remove for platform : `mulle-sde dependency mark mulle-rbtree no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-rbtree/mulle-rbtree.h>   // mulle-rbtree

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove mulle-fprintf`
// (Use B5503F2F-7B31-414A-9C02-4951D21E79C6 instead of mulle-fprintf, if there are duplicate entries)
//
// You can tweak the following #include with these commands:
//    remove #include: `mulle-sde dependency mark mulle-fprintf no-header`
//    rename              : `mulle-sde dependency|library set mulle-fprintf include whatever.h`
//    reorder             : `mulle-sde dependency move mulle-fprintf <up|down>`
//    toggle #include: `mulle-sde dependency mark mulle-fprintf [no-]import`
//    toggle public       : `mulle-sde dependency mark mulle-fprintf [no-]public`
//    toggle optional     : `mulle-sde dependency mark mulle-fprintf [no-]require`
//    remove for platform : `mulle-sde dependency mark mulle-fprintf no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-fprintf/mulle-fprintf.h>   // mulle-fprintf

#endif
