/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_storage_include_h__
#define _mulle_storage_include_h__

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove mulle-container`
// (Use 82BC46EE-7D6E-4270-A605-9D508C778D6E instead of mulle-container, if there are duplicate entries)
//
// You can tweak the following #include with these commands:
//    remove #include: `mulle-sde dependency mark mulle-container no-header`
//    rename              : `mulle-sde dependency|library set mulle-container include whatever.h`
//    reorder             : `mulle-sde dependency move mulle-container <up|down>`
//    toggle #include: `mulle-sde dependency mark mulle-container [no-]import`
//    toggle public       : `mulle-sde dependency mark mulle-container [no-]public`
//    toggle optional     : `mulle-sde dependency mark mulle-container [no-]require`
//    remove for platform : `mulle-sde dependency mark mulle-container no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-container/mulle-container.h>   // mulle-container

#endif
