name: Artifacts

on:
  release:
     types: [published]
  push:
     tags:
     - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64, aarch64]  # not real hardware, just a variable
    steps:
    - name: Set MULLE_HOSTNAME
      run: |
           name="${GITHUB_REF##*/}"
           MULLE_HOSTNAME="${MULLE_HOSTNAME:-ci-${name##*-}}"
           echo "MULLE_HOSTNAME=${MULLE_HOSTNAME}" >> $GITHUB_ENV

    - name: Add to path
      run:  echo "$HOME/bin" >> $GITHUB_PATH

    - name: Dump Environment
      run:  env | sort

    - name: Install sudo if needed
      run: |
           if ! command -v sudo &> /dev/null; then
             apt update
             apt install -y sudo
           else
              sudo apt-get update
           fi

    - name: Install git, curl, developer stuff
      run: |
           sudo apt-get install -y git curl build-essential
           # git config --global --add safe.directory "*"
           
    - uses: actions/checkout@v4

    - uses: mulle-sde/github-ci@v2

    - name: Install rpmbuild
      run:  sudo apt-get update && sudo apt-get install -y rpm

    - name: Install ARM64 toolchain
      if: matrix.arch == 'aarch64'
      run: |
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
              
    - name: Install mulle-project
      run:  |
            mulle-fetch 'https://github.com/mulle-nat/mulle-project/archive/latest.tar.gz' \
            && cd 'mulle-project-latest' \
            && sudo ./bin/installer /usr

    - name: Get version number
      run:  echo "MULLE_CORE_VERSION"=$(mulle-project-version -s) >> $GITHUB_ENV

    - name: Dump Project Environment
      run:  |
            [ ! -d .mulle/etc/env ] || ls -l .mulle/etc/env/environment*.sh
            mulle-sde environment

    - name: Build Debian Package
      run:  |
            mkdir -p package
            cd package
            cmake --version
            cmake -DCMAKE_BUILD_TYPE="Release" \
                  -DCMAKE_SYSTEM_PROCESSOR=${{ matrix.arch }} \
                  -DCMAKE_C_COMPILER=${{ matrix.arch == 'aarch64' && 'aarch64-linux-gnu-gcc' || 'gcc' }} \
                  -DCMAKE_CXX_COMPILER=${{ matrix.arch == 'aarch64' && 'aarch64-linux-gnu-g++' || 'g++' }} ..
            cpack -G DEB
            package="mulle-core_${MULLE_CORE_VERSION}-${{ matrix.arch }}.deb"
            mv *.deb "${package}"
            echo "DEB_PACKAGE=package/${package}" >> $GITHUB_ENV

    - name: Build Redhat Package
      run:  |
            mkdir -p package
            cd package
            cpack -G RPM
            package="mulle-core_${MULLE_CORE_VERSION}-${{ matrix.arch }}.rpm"
            mv *.rpm "${package}"
            echo "RPM_PACKAGE=package/${package}" >> $GITHUB_ENV

    - name: Upload packages (ZIP)
      uses: actions/upload-artifact@v4
      with:
        name: Linux-packages-${{ matrix.arch }}
        path: |
              ${{ env.RPM_PACKAGE }}
              ${{ env.DEB_PACKAGE }}
  
  arch-package:
    if: false  # Arch is broken due to: https://github.com/FFY00/build-arch-package/issues/11
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    container:
      image: archlinux
      options: --privileged --cap-add=SYS_ADMIN --security-opt seccomp=unconfined

    steps:
    - name: Set MULLE_HOSTNAME
      run:  |
            name="${GITHUB_REF##*/}"
            MULLE_HOSTNAME="${MULLE_HOSTNAME:-ci-${name##*-}}"
            echo "MULLE_HOSTNAME=${MULLE_HOSTNAME}" >> $GITHUB_ENV

    - name: Add to path
      run:  echo "$HOME/bin" >> $GITHUB_PATH

    - name: Dump Environment
      run:  env | sort

    - name: Install sudo if needed
      run:  |
            if ! command -v sudo &> /dev/null; then
              pacman -Sy --noconfirm sudo
            fi
           
    - name: Install git, curl, developer stuff
      run:  |
            sudo pacman -Sy --noconfirm git base-devel curl

    - name: Muck around with f*g systemd and new r*t*d git checks
      run:  |
            git config --global --add safe.directory "*"
            # sudo systemctl enable dbus
            # sudo systemctl start dbus
           
    - uses: actions/checkout@v4
 
    - uses: mulle-sde/github-ci@v2
    
    - name: Install mulle-project
      run:  |
            mulle-fetch 'https://github.com/mulle-nat/mulle-project/archive/latest.tar.gz' \
            && cd 'mulle-project-latest' \
            && sudo ./bin/installer /usr

    - name: Get version number
      run:  echo "PROJECT_VERSION"=$(mulle-project-version -s) >> $GITHUB_ENV

    - name: Dump Project Environment
      run:  |
            [ ! -d .mulle/etc/env ] || ls -l .mulle/etc/env/environment*.sh
            mulle-sde environment

    - name: Create PKGBUILD
      run:  mulle-project-pacman-pkg > PKGBUILD

    - name: Initialize pacman key
      run:  |
            sudo pacman-key --init
            sudo pacman-key --populate archlinux
        
    - name: Build Arch Linux package
      uses: mulle-cc/build-arch-package@v2
      env:
        DBUS_SESSION_BUS_ADDRESS: "unix:path=/dev/null"
      with:
        PKGBUILD: PKGBUILD
        OUTDIR: ${{ env.PWD }}/package

    - name: Build Arch Package
      run:  |
            echo "ARCH_PACKAGE=package/*.zst" >> $GITHUB_ENV

    - name: Upload packages (ZIP)
      uses: actions/upload-artifact@v4
      with:
        name: Arch-packages-${{ matrix.arch }}
        path: |
              ${{ env.ARCH_PACKAGE }}
              
  upload-to-release:
    needs: [build]
    if: github.event_name == 'release' || github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]  # not real hardware, just a variable
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: Linux-packages-${{ matrix.arch }}
          path: ./release-files

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./release-files/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
